name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 23.5.0
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run -s typecheck
      - run: pnpm run test -- --run